### PR TITLE
Simplify short-mom->moment for integers

### PR DESCRIPTION
**Pull request by uliska**
AFAICS you can simply feed numbers to ly:make-moment

### CODE REVIEW

**Comment by jpvoigt** [comment]
No, only if the number is *exact*.
`(ly:make-moment 1.5)` will fail, so we need to ask, if the given number is exact, otherwise make it exact:
Try `#(display (ly:make-moment (inexact->exact 3.3)))`
;-) OK better try
`#(display (ly:make-moment (inexact->exact 0.75)))`

**Comment by uliska** [comment]
OK, but then the current implementation is incorrect too (the `(rational? m)` clause).

**Comment by jpvoigt** [comment]
Yes, thats true. I will push a mod in a few seconds!

**Comment by uliska** [comment]
Well, I had already ...

**Comment by jpvoigt** [comment]
... but I have something else ;-)
make-moment can receive any exact number. So if it is a number, make it exact.

**Comment by jpvoigt** [comment]
Now I turn a fraction to one number. The implementation of make-moment might drop the signature with two or four integers in the future.

My tests ran well, I will now merge to master.
Thank you for this PR!

**Pull request merged**
